name: Tests

on:
  push:
  pull_request:

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v7

      - name: Swift version
        run: swift --version

      - name: Build
        run: make build
